name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          FROM_APPVEYOR: 1  # import fix in conftest.py
          CIBW_BEFORE_TEST: pip install -r doc/requirements-test.txt
          CIBW_TEST_COMMAND: "pytest {project}/tests"
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
