name: Build and publish

# Guide: https://scikit-hep.org/developer/gha_wheels

on:
  workflow_dispatch:  # button in UI for manual dispatch
  release:            # new GitHub release
    types:
      - published

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.0
        env:
          FROM_APPVEYOR: 1  # import fix in conftest.py
          CIBW_BEFORE_TEST: pip install -r doc/requirements-test.txt
          CIBW_TEST_COMMAND: "pytest {project}/tests"
          CIBW_SKIP: "pp* cp*-musllinux*"
          #CIBW_BUILD: "cp310*"  # limit for testing?
        # with:
        #   package-dir: .
        #   output-dir: wheelhouse
        #   config-file: "{package}/pyproject.toml"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
  
  build_sdist:
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build sdist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*.tar.gz

  # Alternative workflow:
  # 1. Increment version number, commit & push
  # 2. Trigger build via actions
  # 3. Download artifact, unzip into dist/*
  # 4. `twine upload --repository testpypi dist/*`
  # 5. Enter username & password
  upload_pypi:
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'  # don't upload on manually triggered builds
    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.6.4
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          # for testing:
          #password: ${{ secrets.TEST_PYPI_PASSWORD }}
          #repository_url: https://test.pypi.org/legacy/
